### ISSUE TITLE
Photos with invalid creation date cause exceptions

### ISSUE THREAD

**Issue by sa2000a** [plexinc-plugins/Scanners.bundle#61]
I thought this old problem was flagged to the Devs and added here but cannot find it here.
Just got a new report of the problem

Old forum topic:
https://forums.plex.tv/index.php/topic/129358-bug-pms-fails-to-correctly-addremove-photos-from-photo-libraries/?p=776848

```
Nov 25, 2014 13:24:32:450 [5936] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
File "C:\Users\nucboox\AppData\Local\Plex Media Server\Plug-ins\Scanners.bundle\Contents\Resources\Photos\Plex Photo Scanner.py", line 17, in Scan
created_at = time.localtime(os.path.getmtime(path))
ValueError: (22, 'Invalid argument')
```

New report of the problem:
https://forums.plex.tv/index.php/topic/156682-cannot-add-photos-from-fuji-finepix-sl1000/

```
Apr 06, 2015 13:18:28:845 [344488] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "C:01:20 PM 04/06/2015\Users\lbuchanan\AppData\Local\Plex Media Server\Plug-ins\Scanners.bundle\Contents\Resources\Photos\Plex Photo Scanner.py", line 17, in Scan
    created_at = time.localtime(os.path.getmtime(path))
ValueError: (22, 'Invalid argument')
Apr 06, 2015 13:18:28:845 [344488] ERROR - We got an error scanning in J:\Pictures\SL1000
```

**Comment by elan** [comment]
Is there a piece of sample media? If so, it's valuable to link it inside these issues.
